accounts/urls.py
from django.urls import path
from .views import login, logout, signup

app_name = 'accounts'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
]

main/urls.py
# main의 urls.py 작성
from django.urls import path
from django.contrib import admin
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('product/<int:product_id>/', views.product_detail, name="product_detail"),
    path('product/<int:product_id>/create_comment/', views.create_comment, name="create_comment"),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    id                =   models.AutoField(primary_key=True)
    name              =   models.CharField(max_length=50)
    description       =   models.CharField(max_length=50)
    origin_price      =   models.IntegerField()
    discount_price    =   models.IntegerField()
    discount_rate     =   models.IntegerField()
    category          =   models.ManyToManyField('Category')
    notice            =   models.CharField(max_length=200)
    image_url         =   models.URLField(max_length=2000)

    def summary(self):
        return self.description[:20]
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table    = 'products'

class Category(models.Model):
    name            =   models.CharField(max_length=45)

    def __str__(self):
        return self.name
    class Meta:
        db_table    = 'categories'

class ProductComment(models.Model):
    id              = models.AutoField(primary_key=True)
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    product         = models.ForeignKey('Product', on_delete=models.CASCADE)
    star            = models.IntegerField()
    content         = models.TextField()
    created_at      = models.DateTimeField(auto_now=True)

    class Meta:
        db_table    = 'product_comments'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib.auth.models import User

# Create your views here.
def login_page(request):
    return render(request, 'accounts/login.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage')
        else:
            return render(request, 'accounts/login.html', {'error': '아이디나 비밀번호가 틀렸습니다. 다시 입력해주세요.'})
    else:
        return render(request, 'accounts/login.html', {'error': '로그인 실패'})
    

def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        # username 미입력시 에러
        if not username:
            return render(request, 'accounts/signup.html', {'error': '닉네임을 입력해주세요.'})
        
        # 비밀번호에 영문 대소문자, 숫자, 특수문자 (@ ! ? - _)가 각각 1개 이상 포함되어야 하며 8자 이상이어야 함
        if not (any(c.isupper() for c in password) and any(c.islower() for c in password) and any(c.isdigit() for c in password) and any(c in '@!?-_' for c in password) and len(password) >= 8):
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 조건에 맞지 않습니다. 다시 입력해주세요.'})

        if password == password2:
            if User.objects.filter(username=username).exists():
                return render(request, 'accounts/signup.html', {'error': '이미 사용중인 닉네임입니다.'})
            else:
                user = User.objects.create_user(username=username, password=password)
                auth.login(request, user)
                return redirect('main:mainpage')
        else:
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 일치하지 않습니다.'})
    else:
        return render(request, 'accounts/signup.html')

main/views.py
from django.shortcuts import render, redirect
from .models import Product, ProductComment, Category

# Create your views here.
# 메인페이지와 메인페이지의 products 정보들을 불러오는 함수
def mainpage(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request, 'main/mainpage.html', {'products': products, 'categories': categories})

# 상품의 상세페이지를 불러오는 함수
def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    comments = product.productcomment_set.all()
    return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments})

# 상품의 상세페이지에서 댓글을 작성하는 함수
def create_comment(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        star = request.POST['star']
        content = request.POST['content']
        product.productcomment_set.create(star=star, content=content, user_id=request.user.id)
    return redirect('main:product_detail', product_id)

# 상품의 상세페이지에서 댓글을 삭제하는 함수 (단, 댓글 작성자만 삭제 가능)
def delete_comment(request, comment_id):
    comment = ProductComment.objects.get(id=comment_id)
    product = comment.product
    if request.user.id != comment.user_id:
        comments = product.productcomment_set.all()
        return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments, 'error': '본인의 댓글만 삭제할 수 있습니다.'})
    comment.delete()
    return redirect('main:product_detail', product.id)

accounts/templates/accounts/login.html
<!-- 임시 로그인 페이지 -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/login.css'%}"/>

  <form class="login-container" id="login" method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <div class="login-view">
      <p class="login-title">로그인</p>
      <div class="input-view">
        <input type="text" name="username" id="username" placeholder="아이디를 입력해주세요."/>
        <input type="password" name="password" id="password" placeholder="비밀번호를 입력해주세요."/>
      </div>
      <div class="find-view">
        <p id="find-id">아이디 찾기</p>
        <p>|</p>
        <p id="find-pw">비밀번호 찾기</p>
      </div>
    </div>
    <div class="button-view">
      <button class="disable-btn" disable="disable">로그인</button>
      <button class="sign-btn">회원가입</button>
    </div>
  </form>

  <script src="{% static 'js/accounts/login.js'%}"></script>
{% endblock %}

accounts/templates/accounts/signup.html
<!-- 임시 회원가입 페이지 -->
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/accounts/signup.css'%}"/>

  <div class="sign-up-view">
    <form id="sign-up" class="sign-up-container" action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      <p id="sign-up-title">회원가입</p>
      <div class="line"></div>
      <div class="input-view">
        <div class="username-view">
          <label for="username">아이디</label>
          <input type="text" id="username" placeholder="아이디를 입력해주세요." name="username">
        </div>
        <div class="password-view">
          <label for="pw">비밀번호</label>
          <input type="password" id="pw" placeholder="비밀번호를 입력해주세요." name="password">

        </div>
        <div class="introduction">
          <ul>
            <li>비밀번호를 8자 이상으로 작성해주세요.</li>
            <li>영문 대소문자, 숫자, 특수문자를 하나 이상 포함해주세요.</li>
            <li>사용가능 특수문자 @ ! ? - _</li>
          </ul>
        </div>
        <div class="password-view">
          <label for="pw">비밀번호 확인</label>
          <input type="password" id="pw-check" placeholder="비밀번호를 한번 더 입력해주세요." name="password2">
        </div>
        <p class="check-text hidden-text">비밀번호가 일치하지 않습니다.</p>
      </div>
      <div class="line"></div>
      <button id="submit-btn" class="disabled-status" disabled="disabled" type="submit">가입하기</button>

    </form>

  </div>
  <script src="{% static 'js/accounts/signup.js'%}"></script>
{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <!-- css 파일 -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/main/main_page.css'%}"/>

  <div class="tag-box">
    <div class="tag-list">
      <a class="tag-item tag-selection">인기신상랭킹</a>
      <a class="tag-item">입점특가</a>
      <a class="tag-item">간편한끼</a>
      <a class="tag-item">요즘간식</a>
      <a class="tag-item">주방·리빙</a>
      <a class="tag-item">뷰티</a>
      <a class="tag-item">패션·잡화</a>
    </div>
  </div>
  <div class="contents-wrapper">
    <div class="filter-box">
      <div class="filter-head">
        <p>필터</p>
        <div class="reset-view">
          <img src="{% static 'assets/icons/restart.svg' %}" alt="reset" id="clear">
          <p>초기화</p>
        </div>
      </div>
      <div class="category-box">
        <div class="category-head">
          <p>카테고리</p>
          <img src="{% static "assets/icons/up.svg" %}" alt="up">
        </div>
        <div class="category-list"> 
          <div class="category-item">
            <input type="checkbox" id="check-1">
            <label for="check-1" class="item-name">스킨케어·메이크업</label>
            <span class="item-count" id="count-1">68</span>
          </div>
          <div class="category-item">
            <input type="checkbox" id="check-2">
            <label for="check-2" class="item-name">럭셔리뷰티</label>
            <span class="item-count" id="count-2">24</span>
          </div>
          <div class="category-item">
            <input type="checkbox" id="check-3">
            <label for="check-3" class="item-name">간식·과자·떡</label>
            <span class="item-count" id="count-3">28</span>
          </div>
        </div>
      </div>
    </div>
    <div class="contents-box">
      <div class="sorting-bar">
        <div class="sorting-count">총 508건</div>
        <div class="sorting-list">
          <span class="sorting-item sorting-select">추천순</span>
          <span>|</span>
          <span class="sorting-item">신상품순</span>
          <span>|</span>
          <span class="sorting-item">판매량순</span>
          <span>|</span>
          <span class="sorting-item">혜택순</span>
          <span>|</span>
          <span class="sorting-item">낮은 가격순</span>
          <span>|</span>
          <span class="sorting-item">높은 가격순</span>
        </div>
      </div>
      <div class="category-selection-view hidden-class">
        <div class="category-selection-item hidden-class" id="selection-1">
          <p>스킨케어·메이크업</p>
          <img src="{% static "assets/icons/close.svg" %}" alt="삭제">
        </div>
        <div class="category-selection-item hidden-class" id="selection-2">
          <p>럭셔리뷰티</p>
          <img src="{% static "assets/icons/close.svg" %}" alt="삭제">
        </div>
        <div class="category-selection-item hidden-class" id="selection-3">
          <p>간식·과자·떡</p>
          <img src="{% static "assets/icons/close.svg" %}" alt="삭제">
        </div>
      </div>
      
      
      <div class="product-frame">
        {% for product in products %}
        <div class="product-card">
          <a href="product/{{product.id}}"><img src="{{product.image_url}}"/></a>
          <div class="cart">
            <img src="{% static "assets/icons/cart.svg" %}" alt="카트"/>
            <p>담기</p>
          </div>
          <div class="product-info">
            <p>샛별배송</p>
            <p><a href="product/{{product.id}}">{{product}}</a></p>
            <p>{{product.description}}</p>
            <div class="price-box">
              <p id="origin-price">{{product.origin_price}}원</p>
              <div class="discount-box">
                <p id="discount-rate">{{product.discount_rate}}%</p>
                <p>{{product.discount_price}}원</p>
              </div>
            </div>
          </div>
        </div>
      
      {% endfor %}
      </div>

    </div>
  </div>
  {% comment %}   <a href="product/{{product.id}}">
        </a> {% endcomment %}
  <!-- js 파일 -->
  {% comment %} <div style="display: flex">
    {% for product in products %}
      <a href="product/{{product.id}}">
        <img src="{{product.image_url}}" style="width: 100px"/>
        <p>{{product}}</p>
        <p>{{product.description}}</p>
        <p>{{product.origin_price}}원</p>
        <p>{{product.discount_rate}}%</p>
        <p>{{product.discount_price}}원</p>
      </a>
    {% endfor %}
  </div> {% endcomment %}
  <script src="{% static 'js/main/main_page.js'%}"></script>
{% endblock %}

<!----------------tip!---------------->
<!-- 상품 데이터베이스는 프로젝트에 넣어뒀어요 -->
<!-- 아래와 같은 형식으로 for문을 사용하여 작성하세요 -->

<!-- 데이터 사용 예시 -->

main/templates/main/product_detail_page.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main/product_detail_page.css'%}"/>

  <!-- 코드 작성시, 아래 부분(endblock 이전)은 전체 삭제하고 작성하세요 -->

  <!----------------tip!---------------->
  <!-- 상품 데이터베이스는 프로젝트에 넣어뒀어요 -->
  <!-- 아래와 같은 형식으로 사용하세요 -->

  <div class="frame">
    <div class="info">
      <img src="{{product.image_url}}" alt="product">
      <div class="detail-frame">
        <div class="selection">
          <p>샛별배송</p>
          <div class="product-name">
            <p>{{product.name}}</p>
          </div>
          <div class="product-price">
            <p id="discount">{{product.discount_rate}}%</p>
            <p class="default-price">{{product.discount_price}}
              원</p>
          </div>
          <div class="line"></div>
          <div class="notice-box">
            <p>안내사항</p>
            <p>{{product.notice}}</p>
          </div>
          <div class="line"></div>

          <div class="count-zone">
            <p>상품선택</p>
            <div class="count-box">
              <p>{{product.name}}</p>
              <div>
                <p class="decrement">-</p>
                <p class="total-count">1</p>
                <p class="increment">+</p>
              </div>
            </div>
          </div>
          <div class="line"></div>
        </div>
        <div class="confirm">
          <div class="total-zone">
            <div>
              <p>총 상품 금액:</p>
              <p class="final-price">{{product.discount_price}}
                원</p>
            </div>
          </div>
          <div class="login">
            <p>로그인</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-div">
    <form id="review-from" method="POST" action="create_comment/">
      {% csrf_token %}
      <select name="star" id="star">
        <option value="none">선택</option>
        <option value="1" name="star">1</option>
        <option value="2" name="star">2</option>
        <option value="3" name="star">3</option>
        <option value="4" name="star">4</option>
        <option value="5" name="star">5</option>
      </select>
      <div>
        <textarea placeholder="상품 후기를 남겨주세요" name="content" id="product-review"></textarea>
        <button class="submit-btn" type="submit" disabled="disabled">등록</button>
      </div>
    </form>
  </div>

  <div class="screen">
    <div style="
      width: 1050px;
      display: flex;
      flex-direction: column;
      gap: 20px;
      padding: 20px 0px;
    ">
      {% for comment in comments %}
        <div style="
        display: flex;
        flex-direction: column;
        gap: 16px;
        padding: 20px 8px;
        border-bottom: solid 1px #d9d9d9;
      ">
          <div style="display: flex; justify-content: space-between">
            <p>평점:{{comment.star}}</p>
            <a href="{% url 'main:delete_comment' comment.id %}">삭제</a>
          </div>
          <p class="B1">{{comment.content}}</p>
        </div>
        {% endfor%}
      </div>
    </div>

    <script src="{% static 'js/main/product_detail_page.js'%}"></script>
  {% endblock %}

project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>컬리 - 마켓컬리/뷰티컬리</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base/reset.css'%}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base/style.css'%}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base/font.css'%}"/>
  </head>

  <body>
    <!-- 상단 네브바 -->
    {% include 'shared/_topnav.html' %}
    <!-- 상단 네브바 -->

    <!-- 내용 -->
    {% block content %}{% endblock %}
    <!-- 내용 -->
  </body>

</html>

project/templates/shared/_topnav.html
<!--
최상단 네비게이션을 구현한 topnav 입니다.
3개의 section으로 구분되어있습니다.
-->

<!-- 스타일 css import -->
{% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/shared/topnav.css'%}"
/>

<div class="screen">
  <div class="topnav">
    <!-- 로그인 회원가입 고객센터 -->
    <section class="nav-1 text-font2">
      <div class="div">
        <!-- 로그인을 한 경우 -->
        {% if user.is_authenticated %}
        <p class="Caption">{{user.username}}님 안녕하세요!</p>
        <a class="Caption" href="/accounts/logout/">로그아웃</a>

        <!-- 로그인을 하지 않은 경우 -->
        {% else %}
        <a class="Caption" href="/accounts/signup/">회원가입</a>
        <a class="Caption" href="/accounts/login/">로그인</a>
        {% endif %}

        <div class="Caption">고객센터</div>
      </div>
    </section>

    <!-- 로고 서치바 아이콘들 -->
    <div class="search">
      <a class="logo" href="/">
        <img src="{% static 'assets/logo.svg' %}" />
        <div class="B1-bold text-main">마켓컬리</div>
      </a>

      <form class="search-bar">
        <input class="B2" placeholder="검색어를 입력해주세요" />
        <img
          class="icon-24 icon-main"
          src="{% static 'assets/icons/search.svg' %}"
        />
      </form>

      <div class="iconlist">
        <a>
          <img class="icon-24" src="{% static 'assets/icons/location.svg' %}" />
        </a>
        <a>
          <img class="icon-24" src="{% static 'assets/icons/heart.svg' %}" />
        </a>
        <a>
          <img class="icon-24" src="{% static 'assets/icons/cart.svg' %}" />
        </a>
      </div>
    </div>

    <!-- 카테고리들 -->
    <div class="nav-2 text-font1">
      <button class="category">
        <img class="icon-16" src="{% static 'assets/icons/col-3.svg' %}" />
        <div class="Btn-nav">카테고리</div>
      </button>

      <div class="nav-menu-list Btn-nav" id="nav-menu-list">
        <a href="/"> 신상품 </a>
        <a>베스트</a>
        <a>알뜰쇼핑</a>
        <a>특가/혜택</a>
      </div>

      <a class="right-button B2">
        <div class="text-main">샛별·하루</div>
        <div class="text-font3">배송안내</div>
      </a>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const currentPath = window.location.pathname;

    const navMenu = document.getElementById("nav-menu-list");
    const navMenuList = navMenu.children;

    Array.from(navMenuList).forEach(function (menu) {
      if (menu.href == "http://127.0.0.1:8000" + currentPath) {
        menu.style.color = "#5e0080";
      }
    });

    const searchBarInput = document.querySelector(".search-bar > input");
    searchBarInput.addEventListener("keydown", function (event) {
      if (event.key === "Enter") {
        event.preventDefault();
        const searchTerm = searchBarInput.value;
        alert("검색어: " + searchTerm);
      }
    });
  });
</script>